---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mariadb
  namespace: default
spec:
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: mariadb
      version: 11.5.6
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    image:
      debug: true
    auth:
      existingSecret: mariadb-passwords
      forcePassword: true
      usePasswordFiles: true

    primary:
      persistence:
        existingClaim: default-data
        subPath: mariadb
      podSecurityContext:
        enabled: true
        fsGroup: 65534
