apiVersion: v1
kind: Secret
metadata:
    name: mariadb-passwords
    namespace: default
stringData:
    mariadb-password: ENC[AES256_GCM,data:i6Rf8JyCvf43oMZSX18AXQ==,iv:bvbhw80XvwKJLZIqXsDDIPEm++CYTbN2a007wJtUwQI=,tag:haUsCYRfd78kLVQS1XcRyg==,type:str]
    mariadb-replication-password: ""
    mariadb-root-password: ENC[AES256_GCM,data:xP2EJbgmyDTV7kniU4FA8Q==,iv:MBVBajfxIIYxfLZKscaF3Gkm6b6jJZrhxLe9B8cZsqI=,tag:IrXKnjmWj9Le4hjuVcqCCQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ydxmuen2jv3a9ptg3sp8wcpzuz5chcvaaky2dwsfwmkhsl8leqdqvwxf7m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBreGNzMDFoOStYNGJhRk9P
            V0lTNXZUZWlKYmtCWHg5RStaVlEwQ1pxTDFnCnhzb2NtYVJtSHFSTDRQMW0weXdr
            WnRNY2xlYXc1TXA0bVYzRnN0NTA0WjQKLS0tIHNCdURlZ0VnMlZIOGpRRzRQSWU2
            b0RGaXMvR0pnYjFGaGphNDh0b2JBSm8KiLXIn/4c2DiBCbhuB2TcuMdz3F2fVNb2
            2/UK0slBPZX8XF0pfmmwwRSQMDOuARdtSc3KimcmhQoZkYPvyPB8oQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-27T16:51:47Z"
    mac: ENC[AES256_GCM,data:1/VkqwFUW4ElA8RAxlBkPvgC1TeVidjP5EOG90BV5uZSdxOM+AQoW/JYAUt7ofaB4MXg+XUoVmw08Qm5ez3Rl9MWhFkgbXr4+G+o138xpY+A4BnoA4kSpJ5JLAQbrfTm9PefXZSOrUHGF6C+cALXOKi72iotUhC2dR3Dkb6euiw=,iv:7eHuj1tRjsSh1a6xvZX0vORT8+URxbOzQZj7ZT+EJXY=,tag:UYa3Wvnd8fd13IMiHu8/WA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
