apiVersion: v1
kind: Secret
metadata:
    name: glauth-secret
    namespace: default
type: Opaque
stringData:
    config.cfg: ENC[AES256_GCM,data:xHFXVTTdTHxm8bOJA/xg6dj8eOBRjeB3tqpwlSG2fYs/k2TVcEW0kXIL1ydjRGWS97lQdlXrM0p7w1Ax0WW1gcpnTebL4UIOF+KodNA3Yb8xqxmw2Fi4HBpOpkD283GZ5IBGXbl9qOzK8Egm7JnG3odiwI37FCzjEGFRvcRqtDT8cJF2ZKdk7GrrQ4wnxpPhWGBsTXckRe9Szt1aVy/+Mdn1ZPL7fhQirTHUQTixGjNB72eYbpDx2OEzl4yRT6u1ppCSsQb06E+E3LolNcyQa5zUBMMMu6e7OB86sFoSt6iRas1Dm+Knbx3ZidGVf3fkgU6v8qJcJWhcYKYftTJXMOv93ClMBhqgXc94NeKHJflzHL783X5+MooHZHt2ufyWQ/wzWJnDh9IJyE6Lea5eeQ53/ahG7ZOlEMHU6h8sFoDePKhAwmBKF8TL9Si0K769BZ7hvjxvON+BHdHDgH1mPZbb0lo+U1Ga/895HxW8UFWmbFE4kFS8fMa+Zpr28jsTa4CLWcLMSHFZaTeatIfO0l2+QzIukBr5cUjO+0HpVQOm2NEAm79FPZzSqvypkhciRQPxppMKHyenzsiN5r4RZGERG8u0tgJbPsDJ2Hgfskmw/cSwTZeD7g9evKriP7N0get3qwsgoe6omt53Aa63YbHBavY/Rc0BhyjRWbU+nNwuxDg7DoMfKiWpaFVUIRJlX3r6BcRgTOELc2KQO5tdBV0xKAeaJ/q5rLPcU9W0LjZ1NfGl4/RDeAbbJLAy3GWcgXb+VTWz5d8wbL10igcohYfmKsn+fmgO4CgGNCxRbTonh/kx4y+fX+9xOl125UbhacbKlT8cXFmHQKvVtdnfnD0IxAZna5Z+bLEbbZ8TRZQvYL4YOnNrizNLINUoOuE9BVFxx/HWuQZynfdRpm124X9yRfy9hl0XpV/3ED87rf8JsSEutYE1lFsPZwS47Y6699V6n09K2zQ28dC1wUF59T3zbUxhHFxHtzOocMuf02pNCrUSvW+NCjxLJ0sjqezhWblGI2lVn+XrfWsnSvg409aJXS12rhs00H+5vQnK6a7w4uNSZ7pd4zsqJXdjdVUBtakjtkFglVLwk0yO4v+r8yXMGP6gtwUydhHxLwBt5IhGf5eab3F6s5lCR0AseMo9nc8yyl6oypGI0Vxues5eObkoS0XruOxehg2Iro7zQglevyA9NzZaxVwQn4GFs4xVDd1iMce2PTJXW06+8FTEvR3hE8Wdxm6H/QxippGj0lNZjv82BNHmJ0Aj9KyJc+EuTR+Kbi1AwcLLK4/xnXsXHmiLJ3/2ltPBwX4nSsnvdOHrX07kAOuGhfpGGCSZjxn4a+O9odsZQBjMiy32QLco7C+PFY3P0mxiRts=,iv:QcBdyAWxp4oG0U2l8I8uOx7TNva3G58t2zCvHRMXYUc=,tag:r8Csv11c28kzjp41Wgb/6g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ydxmuen2jv3a9ptg3sp8wcpzuz5chcvaaky2dwsfwmkhsl8leqdqvwxf7m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0bVRnNU4weXI5R0dra3ZT
            aWU3WjhmOGEwT1dIaERCcHJTTC8vQTk5WUVVCkJ6bjBZSGd6clkxL0dDb1phaFFs
            YktyU1dBODc4Y2lDdUhUZVJENElJKzgKLS0tIHpjd2RnSTRpSUNGckxuZnhLLytr
            TEx2dHpDeU4rTlg2d1YvdjFRWHA1VHMKukrc3deJKZiqCcxRtaIjUPSk3xsej/Tl
            PZ22TV1BhUlA6Tg7AQoL8VOsm80J8q0aJtZOXOFnOw9/P3jH/XJe1w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-09T00:52:54Z"
    mac: ENC[AES256_GCM,data:raHkUOmNcOVleljdBShBxI4TqXhFbw0Waf3Xt30EvYrg2ofHPXbkKEE6jdgdxXj/FWD5DrcaAGXce0cIpIzhw1eoJ/4mX4J2r1e1JSBjq2VXDxjsgAfY0oRcz9Ln5zRMB3tqyLKT9ptyEjRHnWjFngCUN3U+3iIW+TFmVB4Lh2s=,iv:lsTIkl3zDsR3mv0RSWqI+dD9YbRz14Lxjqmmnt/bCXA=,tag:fj6JSXqx0ser2eWI/opobg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
