---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app vscode
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: ghcr.io/coder/code-server
      tag: 4.19.1
    env:
      TZ: "${TIMEZONE}"
    args:
      - --auth
      - "none"
      - --user-data-dir
      - "/development/.vscode"
      - --extensions-dir
      - "/development/.vscode"
      - --disable-telemetry
      - --port
      - "12321"
      - "/development"
    securityContext:
      runAsUser: 0
    service:
      main:
        ports:
          http:
            port: 12321
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          # external-dns.alpha.kubernetes.io/target: ipv4.${SECRET_DOMAIN}
          # nginx.ingress.kubernetes.io/auth-method: GET
          # nginx.ingress.kubernetes.io/auth-url: http://authelia.default.svc.cluster.local/api/verify
          # nginx.ingress.kubernetes.io/auth-signin: https://auth.${SECRET_DOMAIN}?rm=$request_method
          # nginx.ingress.kubernetes.io/auth-response-headers: Remote-User,Remote-Name,Remote-Groups,Remote-Email
          # nginx.ingress.kubernetes.io/auth-snippet: proxy_set_header X-Forwarded-Method $request_method;
          hajimari.io/appName: "Development IDE"
          hajimari.io/icon: cib:visual-studio-code
        hosts:
          - host: &host vscode.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: "${SECRET_DOMAIN/./-}-tls"
    persistence:
      development:
        enabled: true
        type: hostPath
        hostPath: /data/vscode
        mountPath: /development
