---
access_control:
  default_policy: two_factor
  networks:
    - name: internal
      networks: ["10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]

  rules:
    - domain:
        - "radarr.${SECRET_DOMAIN}"
        - "sonarr.${SECRET_DOMAIN}"
      policy: bypass
      resources: ["^/api([?/].*)?$"]
    - domain:
        - "grafana.${SECRET_DOMAIN}"
      policy: bypass

identity_providers:
  oidc:
    cors:
      endpoints: ["authorization", "token", "revocation", "introspection"]
      allowed_origins_from_client_redirect_uris: true
    clients:
      - id: "${SECRET_OAUTH_GRAFANA_CLIENTID}"
        description: Grafana
        secret: "${SECRET_OAUTH_GRAFANA_CLIENTSECRET}"
        public: false
        authorization_policy: two_factor
        pre_configured_consent_duration: 1y
        scopes: ["openid", "profile", "groups", "email"]
        redirect_uris: ["https://grafana.${SECRET_DOMAIN}/login/generic_oauth"]
        userinfo_signing_algorithm: none
