---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: paperless
  namespace: default
spec:
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: paperless
      version: 9.1.3
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    image:
      repository: jonaswinkler/paperless-ng
      tag: 1.5.0

    env:
      USERMAP_UID: 1000
      USERMAP_GID: 1000
      PAPERLESS_OCR_LANGUAGE: spa
      PAPERLESS_TIME_ZONE: "${TIMEZONE}"
      PAPERLESS_REDIS: redis://paperless-redis-headless:6379

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        hosts:
          - host: "paperless.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: "${SECRET_DOMAIN/./-}-tls"

    persistence:
      data:
        enabled: true
        type: hostPath
        hostPath: /data/paperless/data
        mountPath: /usr/src/paperless/data
      media:
        enabled: true
        type: hostPath
        hostPath: /data/paperless/media
        mountPath: /usr/src/paperless/media
      consume:
        enabled: true
        type: hostPath
        hostPath: /storage/documents/consume
        mountPath: /usr/src/paperless/consume
      export:
        enabled: true
        type: hostPath
        hostPath: /storage/documents/export
        mountPath: /usr/src/paperless/export

    redis:
      enabled: true
      architecture: standalone
      auth:
        enabled: false
      master:
        persistence:
          existingClaim: paperless-redis

    podSecurityContext:
      fsGroup: 65534
      fsGroupChangePolicy: "OnRootMismatch"
