---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app mosquitto
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: eclipse-mosquitto
      tag: 2.0.15
    podAnnotations:
      reloader.stakater.com/auto: "true"
    service:
      main:
        ports:
          http:
            enabled: false
          mqtt:
            enabled: true
            port: 1883
    configMaps:
      config:
        enabled: true
        data:
          mosquitto.conf: |
            listener 1883
            allow_anonymous true
            persistence true
            persistence_location /mosquitto/data
            connection_messages false
            connection scrypted
            addresses scrypted
            notifications false
            remote_clientid mosquitto
            cleansession true
            topic scrypted/# in
    persistence:
      config:
        enabled: true
        type: configMap
        name: mosquitto-config
        mountPath: /mosquitto/config/mosquitto.conf
        subPath: mosquitto.conf
        readOnly: true
      data:
        enabled: true
        type: hostPath
        hostPath: /data/mosquitto
