---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app authelia
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts/
      chart: app-template
      version: 1.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  dependsOn:
    - name: postgresql
      namespace: default
    - name: glauth
      namespace: default
    - name: redis
      namespace: default
  values:
    controller:
      strategy: RollingUpdate
    image:
      repository: ghcr.io/authelia/authelia
      tag: 4.37.5
    envFrom:
      - secretRef:
          name: *app
    enableServiceLinks: false
    service:
      main:
        ports:
          http:
            port: 80
          metrics:
            enabled: true
            port: 8080
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        hosts:
          - host: "auth.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: "${SECRET_DOMAIN/./-}-tls"
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
    persistence:
      config:
        enabled: true
        type: configMap
        name: *app
        subPath: configuration.yaml
        mountPath: /config/configuration.yaml
        readOnly: false
    podAnnotations:
      configmap.reloader.stakater.com/reload: *app
      secret.reloader.stakater.com/reload: *app
