---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unifi
  namespace: default
spec:
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: unifi
      version: 5.1.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  interval: 5m0s
  values:
    image:
      repository: jacobalberty/unifi
      tag: v7.3.83

    env:
      TZ: "${TIMEZONE}"
      UNIFI_UID: 65534
      UNIFI_GID: 65534
      JVM_MAX_HEAP_SIZE: 1536M

    service:
      main:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: "${SVC_UNIFI_ADDR}"

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        hosts:
          - host: "unifi.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: "${SECRET_DOMAIN/./-}-tls"

    persistence:
      data:
        enabled: true
        type: hostPath
        hostPath: /data/unifi

    resources:
      requests:
        cpu: "0.02"
        memory: "1024M"
      limits:
        memory: "1536M"
