---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kyverno
  namespace: kyverno
spec:
  interval: 15m
  chart:
    spec:
      chart: kyverno
      version: v2.5.2
      sourceRef:
        kind: HelmRepository
        name: kyverno-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    installCRDs: false
    replicaCount: 1
    extraArgs:
      - --autogenInternals=false
      - --clientRateLimitQPS=30
      - --clientRateLimitBurst=60
    serviceMonitor:
      enabled: true
