---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: reflector
  namespace: cert-manager
spec:
  chart:
    spec:
      # renovate: registryUrl=https://emberstack.github.io/helm-charts/
      chart: reflector
      version: 7.0.151
      sourceRef:
        kind: HelmRepository
        name: emberstack
        namespace: flux-system
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
  install:
    remediation:
      retries: 3
  interval: 5m0s
