---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: default
spec:
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: vaultwarden
      version: 5.3.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/vaultwarden
      tag: v1.25.2

    env:
      DATA_FOLDER: "config"
      DOMAIN: "https://vault.${SECRET_DOMAIN}"
      SIGNUPS_ALLOWED: "false"
      SMTP_FROM: "vaultwarden@${SECRET_DOMAIN}"
      SMTP_FROM_NAME: "Vaultwarden"
      TZ: "${TIMEZONE}"
      WEBSOCKET_ADDRESS: 0.0.0.0
      WEBSOCKET_ENABLED: true
      WEBSOCKET_PORT: 3012
    envFrom:
      - secretRef:
          name: vaultwarden

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        hosts:
          - host: "vault.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
              - path: /notifications/hub
                pathType: Prefix
                service:
                  port: 3012
              - path: /notifications/hub/negotiate
                pathType: Prefix
        tls:
          - secretName: "${SECRET_DOMAIN/./-}-tls"

      admin:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          auth.home.arpa/enabled: "true"
        hosts:
          - host: "vault.${SECRET_DOMAIN}"
            paths:
              - path: /admin
                pathType: Prefix
        tls:
          - secretName: "${SECRET_DOMAIN/./-}-tls"

    persistence:
      config:
        enabled: true
        type: hostPath
        hostPath: /data/vaultwarden
        mountPath: /config

    podAnnotations:
      secret.reloader.stakater.com/reload: "vaultwarden"

    podSecurityContext:
      fsGroup: 65534
      fsGroupChangePolicy: "OnRootMismatch"
