# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden
    namespace: default
stringData:
    ADMIN_TOKEN: ENC[AES256_GCM,data:NmgPi2j1xeji7ebE1EXNY+58vO4HzYLY/ruo7ihseXSKR8DilIFGl7bwgpXnZhda2klio8bt/KNTOz2D3f+yng==,iv:0rGQu/0TVzMRvc9w9L/7pWp9VRzyOi3CksSbUvZCtks=,tag:VY/kWgKiRWGlU8roX8tamg==,type:str]
    SMTP_HOST: ENC[AES256_GCM,data:RJUsuz4ayBXilliD9ageOQ==,iv:acZb5Urc2jLHRubDypCtOocn08I+JYuSWjnuXoNOkJs=,tag:bFw7jayjDFpsQGiWW42VDQ==,type:str]
    SMTP_PORT: ENC[AES256_GCM,data:ZQwd,iv:fOqMrzsjGwKMsGFAym84ZQAdO0zaGsSLpqonXfOPqOg=,tag:7FIWAUbGKQteNAiBMYy58w==,type:str]
    SMTP_SSL: ENC[AES256_GCM,data:y3y+Lg==,iv:iIFfsY/rIlhqWfsM+/6xu9o8Z1/FmzKZDo+UHHbftJE=,tag:mMn6D5T3QCvWcjOb+AAvuw==,type:str]
    SMTP_USERNAME: ENC[AES256_GCM,data:HN2EFMi8Ry5lNh1A/kYf01Gi+D3stNg1t2wz4Wd1QxhdiX3WhILf+vitvc9X27x9ctYCx/otNyUXSruDmBs=,iv:RynoeC3WK7WNv7lU42YNabaD2nfrBVIU53u3Ju9wqZI=,tag:9Cg2ujp1CYEfY8Ur0bvVrw==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:UIiTzA6SqpNy9DgCbBW0Pno082LgaEHuEIxG582nMc0=,iv:8frz9quxnnZIAd5L28SABGGdlgcQInWnK7552ynmxp0=,tag:y3JI7vB/XWkJQaMw/kuN3w==,type:str]
    SMTP_AUTH_MECHANISM: ENC[AES256_GCM,data:8SemJ2U=,iv:nCNz4GUQjGOGisP0jmdKNFLOp3hcm6b4bktnLD5+jRw=,tag:V8b28UiVFB8CQ0LS+ZckAQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ydxmuen2jv3a9ptg3sp8wcpzuz5chcvaaky2dwsfwmkhsl8leqdqvwxf7m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0QitZSGFRai9Wellib0w3
            cG1xUE0rNTBkdUk3Uk92WktMYzg4bkdmY1NFCmJMUTg1elJMeDJ6T3NNSnRadjkx
            azQ5THN2SEZuY1R5b2xNTFY1NzF3QjAKLS0tIGxJZThxWXRncUVWcHlnaHlFQkRH
            WVlUbzd6RVdGNlhXOEVOUVU0b0NKUjAKLt7v12LJ+Sefziq68dhvYBBJmsRcXn10
            cW1DWvqF5AMGAAGH0EEtJxCKZGGa2jJC43j5SOPMPx47bUdCRBtocg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-27T16:51:47Z"
    mac: ENC[AES256_GCM,data:QOGm2iT8ffLuJbDxQn8Tp9bdP/LKpSYUnIb7LITvZb9Y20aGOeeyKrOpF6ymdhHfSmvjsfhyrcAZha6G1AEJego6MIsObixmUfu6INZwLMGUzgS5KtTznyPSwR3v4MW+t0eNuHxuiHS9ysk4evKOp+XEGcHs1ebiEFWxmxpNn5A=,iv:xtrokpQkOKgJNnv5bjUyoh19zl+EVbfETEzaQtLAG1U=,tag:EEK0AjS+N49UEckiRJWI6Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
