---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager
  - default
  - flux-system
  - kube-system
  - kyverno
  - media
  - metallb-system
  - monitoring
  - networking
  # - websites
