---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app postgresql
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: postgresql
      version: 11.9.13
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: false
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    nameOverride: *app
    auth:
      existingSecret: *app
      secretKeys:
        adminPasswordKey: POSTGRES_PASSWORD
    architecture: standalone
    primary:
      persistence:
        existingClaim: *app
      podSecurityContext:
        fsGroup: 568
      containerSecurityContext:
        runAsUser: 568
