---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app plex
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts/
      chart: app-template
      version: 1.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: ghcr.io/onedr0p/plex-beta
      tag: 1.32.0.6918-6f393eda1

    env:
      TZ: "${TIMEZONE}"
      # PLEX_CLAIM: "claim-xxx"
      ADVERTISE_IP: "https://${SVC_PLEX_ADDR}:32400/,https://plex.${SECRET_DOMAIN}:443/"
      ALLOWED_NETWORKS: 192.168.0.0/16,10.42.0.0/16
      PLEX_PREFERENCE_1: FriendlyName=plex-k3s
      PLEX_PREFERENCE_2: LanNetworkBandwith=192.168.0.0/16\,10.42.0.0/16

    service:
      main:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: "${SVC_PLEX_ADDR}"
        externalTrafficPolicy: Local
        ports:
          http:
            port: 32400

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
          nginx.ingress.kubernetes.io/configuration-snippet: |
            location = / {
              if ($http_x_plex_device = ""){
                return 301 $scheme://$host/web/index.html;
              }
            }
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: "${SECRET_DOMAIN/./-}-tls"

    persistence:
      config:
        enabled: true
        type: hostPath
        hostPath: /data/plex
        mountPath: /config
      transcode:
        enabled: true
        type: hostPath
        hostPath: /data/plex-transcode
        mountPath: /transcode
      media:
        enabled: true
        type: hostPath
        hostPath: /storage/media
        mountPath: /data

    podSecurityContext:
      runAsUser: 65534
      runAsGroup: 65534
      fsGroup: 65534
