---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: default
spec:
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
      - name: cloudflared
        image: cloudflare/cloudflared:2023.3.1
        imagePullPolicy: IfNotPresent
        command: ["cloudflared"]
        args:
          - --autoupdate-freq
          - 24h0m0s
          - tunnel
          - run
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        volumeMounts:
          - mountPath: /etc/cloudflared
            name: data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
        - name: data
          hostPath:
            path: /data/cloudflared
            type: ""
