---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  - ./authelia/ks.yaml
  - ./bazarr/ks.yaml
  - ./glauth/ks.yaml
  - ./hajimari/ks.yaml
  - ./home-assistant/ks.yaml
  - ./mosquitto/ks.yaml
  - ./plex/ks.yaml
  - ./postgresql/ks.yaml
  - ./prowlarr/ks.yaml
  - ./qbittorrent/ks.yaml
  - ./radarr/ks.yaml
  - ./redis/ks.yaml
  - ./scrypted/ks.yaml
  - ./smtp-relay/ks.yaml
  - ./sonarr/ks.yaml
  - ./vscode/ks.yaml
  - ./zigbee2mqtt/ks.yaml
