---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: home-assistant-srv
  namespace: default
spec:
  config: '{
      "cniVersion":"0.3.1",
      "name":"macvlan-conf",
      "plugins":[
        {
          "type":"macvlan",
          "master":"enp6s0.20",
          "ipam":{
            "type":"static",
            "addresses":[
              {
                "address":"${NAD_SRV_HASSIO_ADDR}",
                "gateway":"${NAD_SRV_GATEWAY}"
              }
            ],
            "dns":{
              "nameservers":[
                "${NAD_DNS}"
              ]
            }
          }
        },
        {
          "type":"sbr"
        }
      ]
    }'
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: home-assistant-iot
  namespace: default
spec:
  config: '{
      "cniVersion":"0.3.1",
      "name":"macvlan-conf",
      "plugins":[
        {
          "type":"macvlan",
          "master":"enp6s0.30",
          "ipam":{
            "type":"static",
            "addresses":[
              {
                "address":"${NAD_IOT_HASSIO_ADDR}",
                "gateway":"${NAD_IOT_GATEWAY}"
              }
            ],
            "dns":{
              "nameservers":[
                "${NAD_DNS}"
              ]
            },
            "routes": [
              {
                "dst": "192.168.30.0/24"
              }
            ]
          }
        }
      ]
    }'
