---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/gitrepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: origin-ca-issuer
  namespace: flux-system
spec:
  interval: 10m
  url: https://github.com/cloudflare/origin-ca-issuer
  ref:
    tag: v0.6.0
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/deploy/charts/
