---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app zigbee2mqtt
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  dependsOn:
    - name: mosquitto
      namespace: default
  values:
    image:
      repository: ghcr.io/koenkk/zigbee2mqtt
      tag: 1.30.3
    env:
      TZ: "${TIMEZONE}"
      ZIGBEE2MQTT_DATA: /config
    service:
      main:
        ports:
          http:
            port: 8080
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        hosts:
          - host: "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: "${SECRET_DOMAIN/./-}-tls"
    securityContext:
      privileged: true
    persistence:
      config:
        enabled: true
        type: hostPath
        hostPath: /data/zigbee2mqtt
        mountPath: /config
      usb:
        enabled: true
        type: hostPath
        hostPath: /dev/ttyUSB0
    resources:
      requests:
        cpu: 50m
        memory: 100Mi
