---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unifi-poller
  namespace: monitoring
spec:
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: unifi-poller
      version: 11.1.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  install:
    remediation:
      retries: 3
  interval: 5m0s
  values:
    image:
      repository: golift/unifi-poller
      tag: 2.1.3
    env:
      TZ: "${TIMEZONE}"
      UP_UNIFI_DEFAULT_URL: "https://${EXT_UNIFI_ADDR}:8443"
      UP_UNIFI_DEFAULT_VERIFY_SSL: false
      UP_UNIFI_DEFAULT_USER: "unifipoller"
      UP_UNIFI_DEFAULT_PASS: "unifipoller"
      UP_UNIFI_DEFAULT_SAVE_SITES: true
      UP_UNIFI_DEFAULT_SAVE_DPI: false
      UP_INFLUXDB_DISABLE: true
      UP_PROMETHEUS_DISABLE: false
    metrics:
      enabled: true
