---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-static-iot-scrypted
  namespace: default
spec:
  config: '{
      "cniVersion":"0.3.1",
      "name":"macvlan-conf",
      "plugins":[
        {
          "type":"macvlan",
          "master": "eno1.30",
          "ipam":{
            "type":"static",
            "addresses":[
              {
                "address": "${NAD_SCRYPTED_ADDR}"
              }
            ]
          }
        },
        {
          "type":"sbr"
        }
      ]
    }'
