---
access_control:
  default_policy: one_factor
  networks:
    - name: internal
      networks: ["10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]

  rules:
    - domain:
        - "radarr.${SECRET_DOMAIN}"
        - "sonarr.${SECRET_DOMAIN}"
      policy: bypass
      resources: ["^/api([?/].*)?$"]
