---
ubuntu:
  packages:
    - apt-transport-https
    - arptables
    - ca-certificates
    - curl
    - ebtables
    - fzf
    - gdisk
    - hdparm
    - htop
    - iputils-ping
    - ipvsadm
    - lm-sensors
    - nano
    - net-tools
    - nfs-common
    - ntpdate
    - nvme-cli
    - psmisc
    - python3-kubernetes
    - python3-yaml
    - smartmontools
    - socat
    - software-properties-common
    - unzip
    - mergerfs
    - xfsprogs
