---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${SECRET_DOMAIN/./-}"
  namespace: networking
spec:
  secretName: "${SECRET_DOMAIN/./-}-tls"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production
  commonName: "${SECRET_DOMAIN}"
  dnsNames:
    - "${SECRET_DOMAIN}"
    - "*.${SECRET_DOMAIN}"
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: ""
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
# ---
# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: "${SECRET_DOMAIN_WEBSITE_01/./-}"
#   namespace: networking
# spec:
#   secretName: "${SECRET_DOMAIN_WEBSITE_01/./-}-tls"
#   issuerRef:
#     kind: ClusterIssuer
#     name: letsencrypt-production
#   commonName: "${SECRET_DOMAIN_WEBSITE_01}"
#   dnsNames:
#     - "${SECRET_DOMAIN_WEBSITE_01}"
#     - "*.${SECRET_DOMAIN_WEBSITE_01}"
#   secretTemplate:
#     annotations:
#       reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
#       reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: ""
#       reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
