---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: dev-vm-hd
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 64Gi
  hostPath:
    path: /data/vms/dev-vm
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dev-vm-hd
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 64Gi
  storageClassName: local-storage
  volumeName: dev-vm-hd
