---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Europe/Madrid"
  #
  SVC_INGRESS_ADDR: "10.45.0.1"
  SVC_K8SGATEWAY_ADDR: "10.45.0.3"
  SVC_PLEX_ADDR: "10.45.0.20"
  SVC_QBITTORRENT_ADDR: "10.45.0.30"
  SVC_SCRYPTED_ADDR: "10.45.0.40"
  #
  NAD_HASSIO_ADDR: "10.1.3.151/24"
  NAD_SCRYPTED_ADDR: "10.1.3.152/24"
  #
  EXT_UNIFI_ADDR: "10.5.0.10"
