---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: samba
  namespace: media
spec:
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: samba
      version: 6.2.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  interval: 5m0s
  install:
    remediation:
      retries: 3
  values:
    image:
      repository: dperson/samba
      tag: latest
      pullPolicy: Always

    env:
      TZ: "${TIMEZONE}"
      USERID: 1000
      GROUPID: 1000

    envFrom:
      - configMapRef:
          name: samba-config
      - secretRef:
          name: samba-users

    service:
      main:
        type: LoadBalancer
        loadBalancerIP: "${SVC_SAMBA_ADDR}"
        externalTrafficPolicy: Local

    persistence:
      documents:
        enabled: true
        type: hostPath
        hostPath: /storage/documents
        mountPath: /documents
      shares:
        enabled: true
        type: hostPath
        hostPath: /storage/shares
        mountPath: /shares

    podSecurityContext:
      fsGroup: 1000
