---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app scrypted
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: ghcr.io/koush/scrypted
      tag: 18-bullseye-lite.s6-v0.7.26

    env:
      TZ: "${TIMEZONE}"

    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false

    service:
      main:
        ports:
          http:
            port: 10080
            primary: true
          mqtt:
            enabled: true
            port: 1883
          https:
            enabled: false
            port: 10443
            protocol: HTTPS
            primary: false
          debug:
            enabled: false
            port: 10081
            protocol: HTTP
            primary: false

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        hosts:
          - host: "scrypted.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: "${SECRET_DOMAIN/./-}-tls"

    persistence:
      config:
        enabled: true
        type: hostPath
        hostPath: /data/scrypted
        mountPath: /server/volume

    podAnnotations:
      k8s.v1.cni.cncf.io/networks: scrypted-srv

    podSecurityContext:
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
