# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:LDf2JbpCQgz5tkcvCnv8OMtO7jXbY9Z01SzS4KKhM5e7hRSTK1y/nw==,iv:Xtr51eE6BTnaW0I/zx5HSdGEyexuOz2BL1rlZfSJGF0=,tag:y54q1SuC08dGjrtsZn+gzQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ydxmuen2jv3a9ptg3sp8wcpzuz5chcvaaky2dwsfwmkhsl8leqdqvwxf7m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFbWpmSzZIL3B2aEwzVEdI
            VXl5dW1mNXFORXlZem5GdWNnTFJmUXY3Ym1VCkdoWlJXbldCdW5PSlRtOHVROTBQ
            dVFGQ3dSQm5YMTJZMENCV1M1S0NCWW8KLS0tIGVsUG1LYk9JMTRHYXpmMEE5WXZS
            amV1NEFEOU1HdENEaDFWTlNpQy8zRDAKURYwo2lgse67uebjSSLhmETG8Cxk30Q2
            8Q8agd8RDOpdSUZtAf0UNeAjZ1T5m4LAvygl36riluIj3aw2CW+HPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-27T16:51:47Z"
    mac: ENC[AES256_GCM,data:4+GLw8gQL+1KgMN9TE1VH6RUmpRlY26/qXYxT90woTJfY3nOwKIbKk2DUkdbuQAauSuH2V5Whm2yeh30EcngyExf+H/9KEMweUS8oD2ZOTUFniU5iNQpVvXboRTfW86Pfj3KgvSpChuYaijQKmhOjyylI9o13L1n+pVlW8X1u/c=,iv:DPcK3gVW5cKlLNnulrLCnYtJhCMRcJq6Aw1PQZWvSxE=,tag:ue+iBVTItu59xyYdqXsLkg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
