---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app authelia
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    initContainers:
      01-init-db:
        image: ghcr.io/onedr0p/postgres-initdb:14.8
        imagePullPolicy: IfNotPresent
        env:
          - name: POSTGRES_HOST
            value: postgresql
          - name: POSTGRES_DB
            value: authelia
          - name: POSTGRES_SUPER_PASS
            valueFrom:
              secretKeyRef:
                name: postgresql-secret
                key: POSTGRES_PASSWORD
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: authelia-secret
                key: POSTGRES_USERNAME
          - name: POSTGRES_PASS
            valueFrom:
              secretKeyRef:
                name: authelia-secret
                key: POSTGRES_PASSWORD
    controller:
      strategy: RollingUpdate
      annotations:
        reloader.stakater.com/auto: "true"
    image:
      repository: ghcr.io/authelia/authelia
      tag: v4.38.0-beta2
    args: ["--config", "/config/configuration.yaml", "--config.experimental.filters", "expand-env"]
    envFrom:
      - secretRef:
          name: authelia-secret
    enableServiceLinks: false
    service:
      main:
        ports:
          http:
            port: &port 80
          metrics:
            enabled: true
            port: 8080
    probes:
      liveness: &probes
        enabled: true
        custom: true
        spec:
          httpGet:
            path: /api/health
            port: *port
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3
      readiness: *probes
      startup:
        enabled: false
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          external-dns.alpha.kubernetes.io/target: ipv4.${SECRET_DOMAIN}
          nginx.ingress.kubernetes.io/configuration-snippet: |
            add_header Cache-Control "no-store";
            add_header Pragma "no-cache";
            add_header X-Frame-Options "SAMEORIGIN";
            add_header X-XSS-Protection "1; mode=block";
          hajimari.io/icon: mdi:shield-account
        hosts:
          - host: &host auth.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: "${SECRET_DOMAIN/./-}-tls"
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: OnRootMismatch
    persistence:
      config:
        enabled: true
        type: configMap
        name: authelia-configmap
        subPath: configuration.yaml
        mountPath: /config/configuration.yaml
        readOnly: false
    resources:
      requests:
        cpu: 5m
        memory: 10Mi
      limits:
        memory: 100Mi
