---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-static-iot-hass
  namespace: default
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": "eno1.30",
      "mode": "bridge",
      "ipam": {
        "type": "static",
        "addresses": [
           {
             "address": "${NAD_HASSIO_ADDR}"
           }
         ]
      }
    }'
