---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: matrix-synapse
  namespace: default
spec:
  chart:
    spec:
      # renovate: registryUrl=https://ananace.gitlab.io/charts
      chart: matrix-synapse
      version: 3.2.5
      sourceRef:
        kind: HelmRepository
        name: ananace
        namespace: flux-system
  interval: 5m
  timeout: 10m0s
  install:
    remediation:
      retries: 3
  values:
    image:
      repository: matrixdotorg/synapse
      tag: v1.80.0

    serverName: "${SECRET_DOMAIN}"
    publicServerName: "matrix.${SECRET_DOMAIN}"

    ingress:
      traefikPaths: true
      className: traefik
      tls:
        - secretName: "${SECRET_DOMAIN/./-}-tls"

    persistence:
      existingClaim: synapse

    config:
      registrationSharedSecret: "${SECRET_MATRIX_REGISTRATION_SHARED}"
      macaroonSecretKey: "${SECRET_MATRIX_MACAROON}"

    extraConfig:
      app_service_config_files:
        - /mautrix-whatsapp/registration.yaml
      modules:
        - module: shared_secret_authenticator.SharedSecretAuthProvider
          config:
            shared_secret: "${SECRET_MATRIX_SHARED_SECRET}"

    synapse:
      extraVolumes:
        - name: mautrix-whatsapp
          hostPath:
            path: /data/mautrix-whatsapp
      extraVolumeMounts:
        - name: mautrix-whatsapp
          mountPath: /mautrix-whatsapp
      extraCommands:
        - 'curl https://raw.githubusercontent.com/devture/matrix-synapse-shared-secret-auth/master/shared_secret_authenticator.py --output /usr/local/lib/python3.8/site-packages/shared_secret_authenticator.py'

    postgresql:
      persistence:
        existingClaim: synapse-postgresql
