---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kyverno
  namespace: kyverno
spec:
  interval: 15m
  chart:
    spec:
      chart: kyverno
      version: 2.7.5
      sourceRef:
        kind: HelmRepository
        name: kyverno
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    crds:
      install: true
    replicaCount: 1
    extraArgs:
      - --clientRateLimitQPS=30
      - --clientRateLimitBurst=60
    grafana:
      enabled: true
    serviceMonitor:
      enabled: true
      interval: 1m
    backgroundController:
      serviceMonitor:
        enabled: true
        interval: 1m
    cleanupController:
      serviceMonitor:
        enabled: true
        interval: 1m
    reportsController:
      serviceMonitor:
        enabled: true
        interval: 1m
