apiVersion: v1
kind: Secret
metadata:
    name: redis-secret
    namespace: default
type: Opaque
stringData:
    REDIS_PASSWORD: ENC[AES256_GCM,data:XWUbYpad1ayJTsKbxeqbMg==,iv:eUoy+XEkl/ihO2OqnO7BhH9phUJsjbH12jO4P7BGZ2o=,tag:Rt2lpP3Xwrm0MfqNK2wdhA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ydxmuen2jv3a9ptg3sp8wcpzuz5chcvaaky2dwsfwmkhsl8leqdqvwxf7m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEenFlcjlwaDd1V2pha0pj
            ZHI1cGRzNjVZOU1rUWt4OFcrRlVTRThVRUNVCkQwczVuOXRZQmVVbGk3eTdxLzdt
            OC9Nb1ZyYm1mUzN4K1QybkxHK3NtN0kKLS0tIHNIdUJpR0k3ZXFsaStBQmM1Qytt
            c3M4eUQrWHRFcXdSdEo5bGtGc2F5MVUKid8J5Hrj2LGuZckWXyRpvTFEg83ndGqG
            bETIYJ3TeWo1EUfp0SECRPA+8KnGexCLIoxMLqLckBLJGjLpeTb9yg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-09T02:26:20Z"
    mac: ENC[AES256_GCM,data:vUUmNoAr/yhC1tvnJjbPOHxHzJt2olKrabLHsPYEswte8Rc9hylu4S801raBnIrR7YohPbuAZnoCHP8rXAesyVtXSqze6AmU2VjbHMY2DNPn6R+dRTiVZHVfxMcD0h8u9rOeygq0cYC0iW81yretm321/fSWTmWlpnBQ6MGEzwQ=,iv:iEIRts7lISFamJkr6HLXnd6KCQhrmrQZnKx5YpRWq6w=,tag:IzUt6IaXpAc62kuTowvJaw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
